---
name: Create Github Issue
description: Creates a new github issue as directly as possible
author: Daniel Barnes
branding:
  icon: alert-octagon
  color: gray-dark
runs:
  using: node20
  main: ./dist/index.js
inputs:
  token:
    description: Your Github PAT, defaults to actions token
    required: false
    default: ${{ github.token }}
  owner:
    description: Repo Owner, if not set implied by context.
    required: false
  repo:
    description: Repo or impiled by the current context
    required: false
  title:
    description: Issue title
    required: false
    default: |
      [${{ github.workflow }}] failure detected
  body:
    description: Body content of issue
    required: false
    default: |
      ## Failure Report:
      
      > [!IMPORTANT]
      > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - Author: @${{ github.triggering_actor }}
      - Branch: `${{ github.ref }}`
      - Commit: ${{ github.sha }}
      - Workflow Path: `${{ github.workflow_ref }}`
  milestone: 
    description: Milestone associated with issue
    required: false
  labels:
    description: CSV of labels (e.x. 'p0-critial,bug,aws')
    required: false
  assignees:
    description: CSV of github usernames to assign (e.x. 'dacbd,nlf')
    required: false
    default: ${{ github.actor }}
outputs:
  json:
    description: The JSON for the new created issue returned from the GitHub API
  html_url:
    description: The web url of the new issue
  number:
    description: "The new issue's number"